language: node_js
node_js:
- stable
deploy:
  provider: heroku
  api_key:
    secure: zVghofDezljDEIDV5qtwvwCSFJUUKPEgOnuug2HzEQ5f7Y5UjaMQ7MSTVENmqpRxKkCm95xOyncn+SDkYE+rbA8npLagBelWfQE0YdVMYEnSTkbZzaNzQMw5HWSmU1Iw5G6Yp1tiYWISe34KHIgRtxHBI4/WVnyemBkDTg/F+7yp6DeiRQMkdRbjR/5esnNTkFIwMY9gxzBRA+aMOIzSQGTKDTMJRYXgLKnCCnztOxzVxJViYYIzoCn65MYGKZqKx40xPJJScSlrOu+XJZOsUxqjKn/aC8c7wl4XaLlQrctMKYKcsUHZ1HV9C1IXIIwSiH6Bh3VV8+B2keFKYdum/ma0+9ZC0z2xPkGo/2bKZCZkkdLUumj4pvUJ/E4elXjueUbwdoIrdTeNe900vAv74g5SOmj6/t7K+JG3cZUYyopCivfg+JGg+csVrQhuPcjO8ld/6tFRYUerGphAE8hRhVJhpne8OPJZcW9nORzvQhkYfYIBq9YdFBZpwVNBsonqx0S/190UiEPI6nbzwXhZ0NWtwVkjyjrCVbtzU6+M6vn1220XNpdWnQG4Vz271LdWIImmUWtVuv/gl/2Vu39NoBQ+jU9TJKh2qw1/S1PAULzzq2s5ewBIHTEABJ+tpIC6lOxoeHO7cHd4OfD6UG4VNpea4pR7Yl1+ptFe2BN7ZeI=
